//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInform
    {
        public int id { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Adress { get; set; }
        public Nullable<double> MapX { get; set; }
        public Nullable<double> MapY { get; set; }
        public string fblink { get; set; }
        public string instalink { get; set; }
    }
}
