//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travel_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelDB : DbContext
    {
        public TravelDB()
            : base("name=TravelDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllTour> AllTours { get; set; }
        public virtual DbSet<ContactInform> ContactInforms { get; set; }
        public virtual DbSet<DiscoverLeft> DiscoverLefts { get; set; }
        public virtual DbSet<DiscoverRight> DiscoverRights { get; set; }
        public virtual DbSet<MoreInformation> MoreInformations { get; set; }
        public virtual DbSet<OurService> OurServices { get; set; }
        public virtual DbSet<OurTeam> OurTeams { get; set; }
        public virtual DbSet<Section2> Section2 { get; set; }
        public virtual DbSet<TopSlider> TopSliders { get; set; }
    }
}
